my_colors
figure();
spider_plot(results([13; 28; 42],2:6),...
    'FillOption', 'off', 'AxesDisplay', 'one',...
    'AxesLimits', [ones(1,5); 4*ones(1,5)],...
    'AxesLabels', {'Width', 'Start Point', 'End Point', 'Angle', 'Offset'}, 'Marker', '.', 'MarkerSize', 20,...
    'Color', colors(1:3,:), 'AxesLabelsEdge', 'none');

exportgraphics(gcf, "best"+".eps", 'BackgroundColor', 'none', 'ContentType', 'vector');

figure();
spider_plot(results([30; 44; 25],2:6),...
    'FillOption', 'off', 'AxesDisplay', 'one',...
    'AxesLimits', [ones(1,5); 4*ones(1,5)],...
    'AxesLabels', {'Width', 'Start Point', 'End Point', 'Angle', 'Offset'}, 'Marker', '.', 'MarkerSize', 20,...
    'Color', colors(1:3,:), 'AxesLabelsEdge', 'none');

exportgraphics(gcf, "worst"+".eps", 'BackgroundColor', 'none', 'ContentType', 'vector');

%% Animated Plot

% [~, rank] = sort(results(:,end), 'descend');
% 
% v = VideoWriter('matlabvideo');
% v.FrameRate = 4;
% v.Quality = 100;
% open(v);
% for i = 1:45
%     spider_plot(results(rank(i),2:6),...
%         'FillOption', 'on', 'AxesDisplay', 'one',...
%         'AxesLimits', [ones(1,5); 4*ones(1,5)],...
%         'AxesLabels', {'Width', 'Start Point', 'End Point', 'Angle', 'Offset'}, 'Marker', '.', 'MarkerSize', 20,...
%         'Color', colors(1,:), 'AxesLabelsEdge', 'none');
%         title(string(i));
%         set(gca, 'FontSize', 15);
%         v.writeVideo(getframe(gcf));
% end
% close(v);